[package]
name = "examsim"
version = "0.0.1"
authors = ["Hubert Jaremko <hjaremko@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
getch = "0.2.1"
colour = "0.5.0"
