name: Build

on: [push]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Build debug
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: cargo build --verbose --all --all-targets
      - name: Upload debug artifact
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: actions/upload-artifact@v2
        with:
          name: examsim-${{ runner.os }}
          path: ./target/debug/examsim*
      - name: Run tests
        run: cargo test --verbose
      - name: Run linter
        run: cargo clippy -- -D warnings

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Build release
        run: cargo build --verbose --release
      - name: Rename macOS artifacts
        if: runner.os == 'macOS'
        working-directory: ./target/release
        run: |
          mv examsim examsim-macos
      - name: Create Linux release
        if: runner.os == 'Linux'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/release/examsim"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
      - name: Create Windows release
        if: runner.os == 'Windows'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/release/examsim.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
      - name: Create macOS release
        uses: ncipollo/release-action@v1
        if: runner.os == 'macOS'
        with:
          artifacts: "./target/release/examsim-macos"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
